Rewrite role to typescript
DevExpress/testcafe pull request #5462
Opened 2020-08-26 14:42 UTC by miherlosev

Changes:
* rewrite Role related files to TypeScript
* use `loginUrl` and `redirectUrl` terms into Role
* add `Role.setCurrentUrlAsRedirectUrl()` method.

2020-08-27 11:32 UTC, miherlosev commented
@testcafe-build-bot retest

2020-08-27 12:42 UTC, miherlosev commented
FPR

2020-08-28 10:22 UTC, AndreyBelym requested changes

2020-08-28 10:22 UTC, AndreyBelym commented on src/api/test-page-url.ts
> +export function resolvePageUrl (url: string, testFileName?: string): string {
The `testFileName` is actually a required argument. When it is not passed, `resolvePageUrl` can throw unexpected errors:
https://github.com/DevExpress/testcafe/issues/3406#issuecomment-514834132
https://stackoverflow.com/questions/60527374/testcafe-throws-an-error-invalid-arg-type

Using `testFileName as string` to suppress type checking errors is dangerous, we should fix the problem by improving the resolution algorithm or by detecting the problem and throwing a descriptive error.

2020-08-31 11:08 UTC, miherlosev commented
FPR

2020-08-31 12:28 UTC, AndreyBelym approved these changes

2020-08-31 16:00 UTC, wentwrong approved these changes

2020-08-31 16:25 UTC, merged