Transfer examples from testcafe-examples
DevExpress/testcafe pull request #5585
Opened 2020-09-28 13:47 UTC by VasilyStrelyaev

Transfer examples from https://github.com/DevExpress/testcafe-examples/pull/22

2020-09-29 05:47 UTC, miherlosev requested changes

2020-09-29 05:47 UTC, miherlosev commented on docs/articles/documentation/guides/basic-guides/obtain-client-side-info.md
> +This example shows the `getLocationPart` client function that returns a [Location](https://developer.mozilla.org/en-US/docs/Web/API/Location) property value. The property name is passed in the `locat
I meet the `passed as parameter` form more often.
Can we change to `The property name is passed as the `locationPart` parameter.`?

2020-09-29 05:47 UTC, miherlosev commented on docs/articles/documentation/reference/test-api/testcontroller/switchtoiframe.md
> +This example shows how to allow more time for an `iframe` to load if the default timeout is not enough.
`if the [default timeout](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--selector-timeout-ms) is not enough`

2020-10-07 06:57 UTC, miherlosev approved these changes

2020-10-07 13:42 UTC, VasilyStrelyaev commented
@testcafe-build-bot /retest

2020-10-08 09:37 UTC, merged