Add .requestHooks to Runner
DevExpress/testcafe pull request #5655
Opened 2020-10-22 22:22 UTC by dpchamps

## Purpose
As a consumer of the TestCafe api, I would like a way to add global requestHooks to tests from the Runner. 

This is valuable for macro-level control over tests. 

Specific use-case: I'm on the platform team that maintains a large mono-repo. We would like a way to add global request hooks to tests without requiring app teams import and consume them. 

## Approach

I looked at the PR that introduced `clientScripts`, and treated the changes to the `Runner` class as a blueprint.

Marking this as a draft PR because I would like some input on how to more sufficiently test, and general feedback on the api change. 

## References
https://github.com/DevExpress/testcafe/issues/5364

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2020-10-23 15:03 UTC, benmonro commented
@miherlosev we would love this on my team as well.

2020-10-27 07:28 UTC, miherlosev commented
Hi @dpchamps

We've fixed issues related to Node 15 and Firefox 82. You need to rebase the gh5364 branch to make tests passed.

2020-10-27 23:48 UTC, dpchamps commented
@miherlosev did the rebase. Looks like azure-mobile is still timing out. Anything I can do to help on this front?

2020-10-29 07:42 UTC, miherlosev commented
> @miherlosev did the rebase. Looks like azure-mobile is still timing out. Anything I can do to help on this front?

It's an issue with Azure Pipeline. I restarted the tests. You can continue working on this PR despite timeout problems with Azure tasks.

2020-10-29 20:23 UTC, dpchamps commented
@miherlosev I was hoping to get some feedback before continuing: 

1. Is this an acceptable change to the api?
1. Is the surface area too small
1. What would you consider sufficient tests for this api change?

2020-11-02 07:26 UTC, miherlosev commented
Hi @dpchamps 

In general, your PR is OK. We will review it at the start of the next development sprint (after 10 November).

2020-11-05 08:20 UTC, miherlosev requested changes

2020-11-05 08:20 UTC, miherlosev commented on src/runner/index.js
> +    async _prependRequestHooks (tests, requestHooks) {
Remove `async` keyword.

2020-11-05 08:20 UTC, miherlosev commented on test/server/runner-test.js
> +        it('Should raise an error for multiple ".requestHooks" method call', () => {
Add a functional test to the `test/functional/fixtures/api/es-next/request-hooks/test.js` file. The test should check the hook execution order (the first - common request hooks, the next - test's request hooks).

2020-12-03 13:37 UTC, miherlosev commented
Hi @dpchamps

Thank you for your work. This PR is good.
However, we decided to use another approach to implement this feature. The main reason is that we want to provide a way to set up global actions not only via the programmatic API.
So, I will close this PR.

Global setup actions will be placed into special files. Such an approach allows you to use all the configuration interfaces: command-line, programmatic, and the configuration file. See the draft feature description at [https://github.com/DevExpress/testcafe/issues/4323#issuecomment-737894637](https://github.com/DevExpress/testcafe/issues/4323#issuecomment-737894637)

2020-12-03 13:37 UTC, closed without merging