Configure request timeouts (close #2940)
DevExpress/testcafe pull request #5692
Opened 2020-11-10 06:16 UTC by miherlosev

Changes:
* added `pageRequestTimeout`, `ajaxRequestTimeout` options
* remove `test-functional-local-multiple-windows` task since the `multiple-windows` feature became enabled by-default.
* rewrite `src/test-run/client-messages.js` and `src/test-run/phase.ts` files to TypeScript

Related [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2470) in hammerhead.

2020-11-16 10:01 UTC, AlexKamaev requested changes

2020-11-16 10:01 UTC, AlexKamaev commented on test/functional/fixtures/multiple-windows/test.js
> +if (config.useLocalBrowsers && !config.useHeadlessBrowsers) {
There is the `!config.useHeadlessBrowsers` condition. However, if we remove the separate `multiple-windows` task we will have only the `test-functional-local-headless-chrome`. Thus, these tests will be ignored

2020-11-21 08:15 UTC, miherlosev commented
FPR

2020-11-23 08:18 UTC, AlexKamaev approved these changes

2020-12-11 16:05 UTC, VasilyStrelyaev commented on src/cli/argument-parser.ts
> +            .option('--ajax-request-timeout <ms>', 'specify the time within which ajax request (xhr or fetch) should be completed')
```
            .option('--page-request-timeout <ms>', 'specify the time within which the request for page HTML should be completed')
             .option('--ajax-request-timeout <ms>', 'specify the time within which AJAX requests (XHR or fetch) should be completed')
```

2020-12-11 16:12 UTC, VasilyStrelyaev commented on src/cli/argument-parser.ts
> +            .option('--ajax-request-timeout <ms>', 'specify the time within which ajax request (xhr or fetch) should be completed')
Although... We should wait for Dirk...

2020-12-14 10:29 UTC, VasilyStrelyaev requested changes

2020-12-14 10:29 UTC, VasilyStrelyaev commented on src/cli/argument-parser.ts
> +            .option('--ajax-request-timeout <ms>', 'specify the time within which ajax request (xhr or fetch) should be completed')
Checked with Dirk:

```js
            .option('--page-request-timeout <ms>', 'specifies the timeout in milliseconds to complete the request for the page's HTML')
            .option('--ajax-request-timeout <ms>', 'specifies the timeout in milliseconds to complete the AJAX requests (XHR or fetch)')
```

2020-12-18 10:50 UTC, VasilyStrelyaev approved these changes

2020-12-18 14:24 UTC, AndreyBelym approved these changes

2020-12-21 07:28 UTC, merged