fix(server-tests): test doesn't properly stub stdout
DevExpress/testcafe pull request #5717
Opened 2020-11-18 07:39 UTC by wentwrong

Test for "debug" method of the test controller doesn't properly stub the stdout stream, which causes the method's code to interfere with mocha's spec reporter's output. As a result, we see broken output after the `gulp test-server` command is executed.

before:
![before](https://user-images.githubusercontent.com/26363017/99499627-3cf75580-298a-11eb-9580-231874ee72ba.png)

after:
![after](https://user-images.githubusercontent.com/26363017/99499638-41237300-298a-11eb-861c-36c13ce7d7e9.png)

2020-11-18 08:14 UTC, miherlosev requested changes

2020-11-18 08:14 UTC, miherlosev commented on test/server/execute-async-expression-test.js
> +class StubStream {
Try to use an appropriate stream from test/functional/utils/stream.js

2020-11-18 18:27 UTC, wentwrong commented
@testcafe-build-bot retest

2020-11-19 07:16 UTC, miherlosev approved these changes

2020-11-19 07:16 UTC, merged