continue browser restart if close browser hangs (closes #5238)
DevExpress/testcafe pull request #5731
Opened 2020-11-22 11:04 UTC by AlexKamaev

2020-11-23 11:36 UTC, miherlosev requested changes

2020-11-23 11:36 UTC, miherlosev commented on src/browser/connection/index.ts
> +const DEBUG_SCOPE = (id: string): string => `testcafe:browser:connection:${id}`;
I suggest to rename this constant as `const getBrowserConnectionDebugScope = (id: string)...`

2020-11-23 11:36 UTC, miherlosev commented on src/browser/connection/index.ts
> +        const restartPromise = timeLimit(this._closeBrowser(), this.BROWSER_CLOSE_TIMEOUT, { resolveWith: void 0, rejectWith: new TimeoutError() })
You can remove the `resolveWith: void 0` statement.

2020-11-24 10:58 UTC, miherlosev approved these changes

2020-11-24 16:14 UTC, AndreyBelym approved these changes

2020-11-27 08:32 UTC, merged