fix(tests): mocha timeout is always set to Infinity
DevExpress/testcafe pull request #5739
Opened 2020-11-24 16:15 UTC by wentwrong

## Purpose
Server tests are run with a specifed Mocha "timeout" option, which should be equal to "Infinity" when tests are executed under the debugger and 2000 ms otherwise. But the [condition](https://github.com/DevExpress/testcafe/blob/6e7a44d9cdc2bbb8927c4a89cf69816ec0862016/Gulpfile.js#L383) that is supposed to implement this logic actually always returns `true`, and so the timeout is always being set to "Infinity". This condition doesn't properly detect debug mode because `typeof v8debug` always returns `undefined` in node versions >= 7 and `process.debugPort` is always set.

## Approach
Checking that `typeof v8debug !=== undefined` and [process.execArgv](https://nodejs.org/api/process.html#process_process_execargv) contains "debug" or "inspect" strings. This probably doesn't cover every case, because seems that currently there is no universal and official way to check if code is being run under the debugger (nodejs/node#9617), but it works well enough.

2020-11-24 20:42 UTC, wentwrong commented
@testcafe-build-bot retest

2020-11-26 05:26 UTC, miherlosev requested changes

2020-11-26 05:26 UTC, miherlosev commented on Gulpfile.js
> +const IS_DEBUG_MODE = typeof v8debug !== 'undefined' || /--debug|--inspect/.test(process.execArgv.join(' '));
Create function `getTimeout(timeout)` and move it to the `gulp/helpers/get-timeout.js` file.
Also add the !gulp statement to the .gitignore file - https://github.com/DevExpress/testcafe/pull/5724/files#diff-2f754321d62f08ba8392b9b168b83e24ea2852bb5d815d63e767f6c3d23c6ac5R3

2020-11-26 13:32 UTC, miherlosev approved these changes

2020-11-27 00:28 UTC, AndreyBelym approved these changes

2020-11-27 00:29 UTC, merged