[docs] Update the website 12/23/2020
DevExpress/testcafe pull request #5827
Opened 2020-12-23 13:55 UTC by VasilyStrelyaev

Merge to update the website.

Preview at: https://vasilystrelyaev.github.io/testcafe/

* Added @Farfurix's article [Randomize Your End-to-End Tests: How to Generate Input Data for TestCafe](https://vasilystrelyaev.github.io/testcafe/media/team-blog/randomize-your-end-to-end-tests-how-to-generate-input-data-for-testcafe.html)
* Fixed an issue when the [shadowRoot](https://vasilystrelyaev.github.io/testcafe/documentation/reference/test-api/selector/shadowroot.html) reference topic was absent from the nav menu

2020-12-23 13:58 UTC, andnaz approved these changes

2020-12-23 14:23 UTC, Farfurix requested changes

2020-12-23 14:23 UTC, Farfurix commented on media/team-blog/randomize-your-end-to-end-tests-how-to-generate-input-data-for-testcafe.html
> +<span class="kd">const</span> <span class="nx">invalidPasswords</span> <span class="o">=</span> <span class="nx">shortPasswords</span><span class="p">.</span><span class="nx">concat</span><span class
```suggestion
<span class="kd">const</span> <span class="nx">invalidPasswords</span> <span class="o">=</span> <span class="nx">shortPasswords</span><span class="p">.</span><span class="nx">concat</span><span class="p">(</span><span class="nx">passwordsWithoutUppercase</span><span class="p">,</span> <span class="nx">passwordsWithoutLowercase</span><span class="p">,</span> <span class="nx">passwordsWithoutDigits</span><span class="p">);</span>
```

2020-12-23 14:23 UTC, Farfurix commented on media/team-blog/randomize-your-end-to-end-tests-how-to-generate-input-data-for-testcafe.html
> +<span class="kd">const</span> <span class="nx">invalidPasswords</span> <span class="o">=</span> <span class="nx">shortPasswords</span><span class="p">.</span><span class="nx">concat</span><span class
https://github.com/Farfurix/Generating-input-data/blob/main/tests/form-validation-test.js#L69

2020-12-28 14:47 UTC, Farfurix approved these changes

2020-12-28 14:47 UTC, merged