[docs] Add changelog for v1.10.1
DevExpress/testcafe pull request #5828
Opened 2020-12-23 16:06 UTC by VasilyStrelyaev

2020-12-24 05:50 UTC, Farfurix requested changes

2020-12-24 05:50 UTC, Farfurix commented on CHANGELOG.md
> +## v1.10.1 (2020-12-23)
```suggestion
## v1.10.1 (2020-12-24)
```

2020-12-24 06:23 UTC, miherlosev commented
@testcafe-build-bot retest

2020-12-30 09:33 UTC, Farfurix approved these changes

2020-12-30 12:00 UTC, merged