Add ability to specify Testcafe Configuration Path
DevExpress/testcafe pull request #6035
Opened 2021-03-10 13:34 UTC by Chris-Greaves

## Purpose
Add the ability to specify the Testcafe config to use, instead of the default `.testcaferc.json` file. This is very useful for Monorepos, Pipelines and QoL for developers.

## Approach
I added this functionality by extending the object passed into the `createTestCafe` method and adding checks to ensure the addition doesn't cause a breaking change.

## References
This is a solution to issue #3428 

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

2021-03-11 11:14 UTC, miherlosev requested changes
Thank you for contributing to the TestCafe. In general, your PR is great. I left some comments related to code style and formatting.

2021-03-11 13:37 UTC, Chris-Greaves commented
@miherlosev Will look at making these changes this evening ready for tomorrow. Also need to update the docs so will do that.

2021-03-11 13:49 UTC, Chris-Greaves commented on test/server/configuration-test.js
> +            const customConfigPath = 'custom11.testcaferc.json';
Did you want the new line between 652 and 653, or between 653 and 654?

2021-03-11 13:59 UTC, miherlosev commented on test/server/configuration-test.js
> +            const customConfigPath = 'custom11.testcaferc.json';
Between 653 and 654

2021-03-11 14:12 UTC, Chris-Greaves commented on src/cli/argument-parser.ts
> +    configPath?: string;
Do you want me to change the cli flag to `--config-file` as well?

2021-03-11 18:37 UTC, Chris-Greaves commented
@miherlosev Your comments should be resolved now, and the docs have been updated to include the new functionality. Any problems let me know.

2021-03-11 23:05 UTC, Chris-Greaves commented
Looks like the "continuous-integration-azure-mobile" check failed due to it taking too long, I'm guessing I can leave that to you guys to re-run or whatever?

2021-03-12 06:08 UTC, miherlosev approved these changes

2021-03-12 06:12 UTC, miherlosev commented
https://github.com/DevExpress/testcafe/pull/6035

> Looks like the "continuous-integration-azure-mobile" check failed due to it taking too long, I'm guessing I can leave that to you to re-run or whatever?

Yes, we will rerun this task.

@DIRECTcut check please documentation and option CLI description

2021-03-16 07:48 UTC, DIRECTcut commented
@Chris-Greaves 

Hello and thank you for this awesome PR!

As our [contribution guidelines](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#documentation-for-new-features) suggest, documentation for new features should be committed to the `new-docs` branch. This is necessary to keep our website ready to publish at all times.

Please transfer all documentation changes to a new branch and open a pull request from there.
When the new PR is ready, feel free to request a review from me. Please open the branch for commits (I may need to commit some edits).

Thanks.

2021-03-16 10:20 UTC, Chris-Greaves commented
@DIRECTcut I have created a new PR (#6053) for the docs and have referenced this outstanding PR. It should be open for you to make changes as well if needed. I have also reverted the changes to the docs from this PR so it isn't duplicated.

Just let me know if there is anything else you need me to do 😄

2021-03-17 05:59 UTC, miherlosev approved these changes

2021-03-17 08:57 UTC, DIRECTcut commented on src/cli/argument-parser.ts
> +            .option('--config-file <path>', 'use a different testcafe config to the default and specify its location')
```suggestion
            .option('--config-file <path>', 'specify a custom path to the testcafe configuration file')
```

2021-03-17 09:00 UTC, DIRECTcut approved these changes

2021-03-17 12:25 UTC, Chris-Greaves commented
@miherlosev I noticed that my branch is something like 13 commits behind master, did you need me to rebase the changes or anything?

2021-03-17 12:25 UTC, miherlosev commented
All tests are green
* all tasks are green (except few `Travis CI` tasks) https://github.com/DevExpress/testcafe/pull/6035#issuecomment-801017080
* all Travis CI tasks are green https://travis-ci.com/github/testcafe-build-bot/testcafe/builds/220355952

2021-03-17 12:26 UTC, merged

2021-03-17 12:49 UTC, miherlosev commented
The feature will be shipped with the next TestCafe version. We are going to release it in a few days.