[docs] Add note about multiple windows in custom browsers
DevExpress/testcafe pull request #6058
Opened 2021-03-18 13:26 UTC by DIRECTcut

fixes #5963

2021-03-19 07:06 UTC, AlexKamaev approved these changes

2021-03-22 10:49 UTC, titerman requested changes

2021-03-22 10:49 UTC, titerman commented on docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md
> +Multiple browser windows are not available in browsers launched with a [custom browser provider plugin](../extend-testcafe/browser-provider-plugin.md). If you use actions that only work in the multip
Avoidable *double* passive voice

```suggestion
Custom [browser provider plugins](../extend-testcafe/browser-provider-plugin.md) do not provide support for multiple browser windows. If TestCafe encounters a window management action (for example, [t.openWindow](../../reference/test-api/testcontroller/openwindow.md)) during a custom browser test, it stops test execution and throws an error.
```

2021-03-22 11:03 UTC, DIRECTcut commented on docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md
> +Multiple browser windows are not available in browsers launched with a [custom browser provider plugin](../extend-testcafe/browser-provider-plugin.md). If you use actions that only work in the multip
```suggestion
Custom [browser provider plugins](../extend-testcafe/browser-provider-plugin.md) do not provide support for multiple browser windows. If TestCafe encounters a window management action (for example, [t.openWindow](../../reference/test-api/testcontroller/openwindow.md)) during a test in a custom browser, it stops test execution and throws an error.
```

2021-03-22 11:23 UTC, titerman approved these changes

2021-03-23 11:39 UTC, dirk-pieterse approved these changes

2021-03-24 08:33 UTC, merged