dispatch event base
DevExpress/testcafe pull request #6103
Opened 2021-04-01 15:19 UTC by AlexKamaev

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-04-02 12:45 UTC, miherlosev requested changes

2021-04-02 12:45 UTC, miherlosev commented on src/client/automation/playback/dispatch-event.js
> +import hammerhead from '../deps/hammerhead';
Rewrite all new files with TypeScript.

2021-04-02 13:18 UTC, miherlosev approved these changes

2021-04-08 09:56 UTC, AndreyBelym approved these changes

2021-04-08 09:56 UTC, merged