fix TestCafe hangs during TestCafe Studio tests (closes #5207)
DevExpress/testcafe pull request #6169
Opened 2021-04-23 10:02 UTC by AlexKamaev

2021-04-26 10:58 UTC, miherlosev requested changes

2021-04-26 10:58 UTC, miherlosev commented on test/functional/fixtures/regression/gh-5207/test.js
> +}
You can simplify creation of the custom reporter using the `createReporter` utility function.
```js
import createReporter from 'test/functional/utils/reporter.js'

createReporter({
  reportTestDone: async () {
      return new Promise(resolve => {
          setTimeout(resolve, 5000);
       });
  }
})

```

2021-04-26 23:44 UTC, AndreyBelym approved these changes

2021-04-27 05:52 UTC, miherlosev approved these changes

2021-04-27 08:08 UTC, merged