feat: added supporting custom properties in .testcaferc.json
DevExpress/testcafe pull request #6293
Opened 2021-06-09 14:59 UTC by Aleksey28

[closes DevExpress/testcafe#3593]

## Purpose
Added possibility to use custom properties in the configuration file

## Approach
1. Add test for feature
2. Add an API to get the UserConfig, which is filled in information from the 'userConfig' property from the configuration file 

## References
https://github.com/DevExpress/testcafe/issues/3593

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-06-25 12:24 UTC, AndreyBelym approved these changes
Awesome

2021-06-25 14:59 UTC, miherlosev requested changes

2021-06-25 14:59 UTC, miherlosev commented on src/api/user-variables/index.js
> +export default {
Rewrite the new files with TypeScript

2021-06-25 14:59 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/testcafe-fixtures/user-variables-test.js
> +import { expect } from 'chai';
Why do we use `expect` assertion instead of TestCafe's assertions?

2021-06-25 14:59 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/test.js
> +});
You added the test covering the 'read; capability. Add the test for 'write' capability.
Like this one:

```js
import { userVariables } from 'testcafe';

fixture `Write access`
    .before({
        userVariables.executedTests = [];
     })
    .after(() => {
      await t.expect(userVariables.executedTests).eql(['1', '2', '3']);
   })

test('1', async t => {
   userVariables.executedTests.push('1');
});

test('2', async t => {
      userVariables.executedTests.push('2');
});

test('3', async t => {
        userVariables.executedTests.push('3');
});
```

2021-06-25 14:59 UTC, miherlosev commented on test/server/data/test-suites/typescript-defs/user-variables.ts
> +import { expect } from 'chai';
Why do we use expect assertion instead of TestCafe's assertions?

2021-06-28 14:16 UTC, Aleksey28 commented
FPR

2021-06-28 14:48 UTC, miherlosev requested changes

2021-06-28 14:48 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/test.js
> +    it('Should provide user variables for read', function () {
```js
it('Read', () => {
    return runTests('./testcafe-fixtures/read.js', 'test', DEFAULT_RUN_OPTIONS);
}
it('Write', () => { 
    return runTests('./testcafe-fixtures/write.js', 'test', DEFAULT_RUN_OPTIONS);
}
```

2021-06-28 14:48 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/testcafe-fixtures/readable-test.js
> +    await t.expect(url).eql('localhost');
Code style.

Combine to one chain here and below.
```js
await t
    .expect(url).eql('localhost')
    .expect(port).eql(1337)
    .expect(isUserVariables).eql(true);
```

2021-06-28 14:48 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/testcafe-fixtures/writable-test.js
> +    userVariables.executedTests.push('localhost');
A little bit shorter:

`userVariables.executedTests.push('localhost', 1337, true);`

2021-06-28 14:48 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/testcafe-fixtures/writable-test.js
> +        expect(userVariables.executedTests).eql(['localhost', 1337, true]);
```js
.after(t => {
     await t.expect(userVariables.executedTests).eql(['localhost', 1337, true]);
})
```

2021-06-28 14:48 UTC, miherlosev commented on test/functional/fixtures/api/es-next/user-variables/testcafe-fixtures/writable-test.js
> +import { expect } from 'chai';
Remove the `chai` import.

2021-06-29 08:16 UTC, miherlosev requested changes

2021-06-29 08:16 UTC, miherlosev commented on test/server/data/test-suites/typescript-defs/user-variables.ts
> +    await t.expect(url).eql('localhost');
```js
await t
    .expect(url).eql('localhost')
    .expect(port).eql(1337)
    expect(isUserVariables).eql(true)
```

2021-06-29 08:23 UTC, miherlosev approved these changes

2021-07-15 13:05 UTC, miherlosev approved these changes

2021-08-17 07:33 UTC, miherlosev commented
Rebase please.

2021-08-20 06:59 UTC, merged