feat: added verification of the existence of the configuration file
DevExpress/testcafe pull request #6381
Opened 2021-07-13 11:46 UTC by Aleksey28

[closes DevExpress/testcafe#6337]

## Purpose
Show an error if the explicitly configuration file doesn't exist

## Approach
1. Add a test with getting an error
2. Add a new error type
3. Add a condition for the existence of the configuration file

## References
https://github.com/DevExpress/testcafe/issues/6337

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-07-13 12:49 UTC, miherlosev approved these changes

2021-07-13 13:07 UTC, titerman approved these changes

2021-07-16 07:27 UTC, miherlosev requested changes

2021-07-16 07:27 UTC, miherlosev commented on src/errors/runtime/templates.js
> +    [RUNTIME_ERRORS.cannotFindTestcafeConfigurationFile]: '"{filePath}" is not a valid TestCafe configuration file.',
Need to change message text. 
At present, it tells about valid/invalid file. It should tell about the fact that file is not found by specified path.

2021-08-02 13:23 UTC, AlexKamaev approved these changes

2021-08-12 15:09 UTC, miherlosev approved these changes

2021-08-12 15:10 UTC, merged