attempt to integrate esm module for compiler service
DevExpress/testcafe pull request #6384
Opened 2021-07-14 14:28 UTC by AlexKamaev

2021-08-06 06:21 UTC, AndreyBelym approved these changes

2021-08-09 07:36 UTC, AlexKamaev commented
I tested this PR with the following page model (+ I tested different combination of js and ts files):
```JS
import { Selector } from 'testcafe';

class PageModel {
    public header: any;

    constructor () {
        this.header = Selector('h1');
    }
}

export default new PageModel();
```

```JS
import { Selector } from 'testcafe';

import pageModel from './page-model';

fixture `f`
    .page `http://example.com`;

test('test', async t => {
    await t.click(pageModel.header);
});

```

2021-08-09 11:22 UTC, AlexKamaev commented on src/compiler/test-file/api-based.js
> +                global.customExtensionHook = null;
remove this line

2021-08-09 13:57 UTC, miherlosev requested changes

2021-08-09 13:57 UTC, miherlosev commented on src/compiler/compilers.js
> +function createTestFileCompilers (options = {}, isExternalServiceMode) {
`isCompilerServiceMode`

2021-08-10 10:58 UTC, miherlosev approved these changes

2021-08-10 10:59 UTC, miherlosev commented
Don't merge it until `1.15.2` is released.

2021-08-11 13:08 UTC, merged