test
DevExpress/testcafe pull request #6406
Opened 2021-07-21 15:17 UTC by AlexKamaev

2021-07-22 09:24 UTC, AndreyBelym approved these changes
The failed test actually cannot pass in `master` when started alone. I think we can fix it outiside of this PR.

2021-08-05 07:58 UTC, helen-dikareva approved these changes
It works properly for the initial case in Studio

2021-08-05 07:58 UTC, helen-dikareva commented on src/compiler/test-file/api-based.js
> +            .split(pathSep)[0] === 'lib';
(minor)
maybe it's better to extract `'lib'` as s const

2021-08-06 07:10 UTC, AlexKamaev commented
Do not merge this PR please. It seems that the tests fail consistently.

2021-08-06 14:34 UTC, AlexKamaev commented
I removed special cache key for the first compiler.
I disabled this new approach for live mode

2021-08-09 07:27 UTC, miherlosev requested changes

2021-08-10 11:00 UTC, miherlosev approved these changes

2021-08-10 12:08 UTC, AndreyBelym approved these changes

2021-08-13 11:05 UTC, merged