fix: the reporter.reportTestActionDone doesn't work with raw API tests
DevExpress/testcafe pull request #6443
Opened 2021-08-09 10:13 UTC by Aleksey28

[closes DevExpress/testcafe#6425]

## Purpose
The reporter.reportTestActionDone should work with raw API tests

## Approach
1. Added call executeAction and executeCommand via one method.
2. Call executeAction instead of executeCommand in the RawTestFileCompiler

## References
https://github.com/DevExpress/testcafe/issues/6425

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-08-25 08:17 UTC, miherlosev requested changes

2021-08-25 08:17 UTC, miherlosev commented on src/api/test-controller/assertion.ts
> +    private _enqueueAssertion (command: unknown, assertionArgs: AssertionArgs): () => Promise<unknown> {
Can we use more strict type here (for example, `AssertionCommand`)?

2021-08-25 08:17 UTC, miherlosev commented on src/live/test-run.js
> +        _executeInternalCommand (commandToExec, callsite, forced) {
`_internalExecuteCommand`

2021-08-25 08:17 UTC, miherlosev commented on src/services/serialization/replicator/transforms/command-base-trasform/command-constructors.ts
> +    SwitchToIframeCommand, SwitchToMainWindowCommand,
Formatting

2021-08-25 08:17 UTC, miherlosev commented on src/test-run/commands/assertion.d.ts
> +export class Eql extends AssertionCommand {}
I propose to use the long class name (`EqlAssertionCommand`) because the current class name (`Eql`) looks like enum.

2021-08-25 08:17 UTC, miherlosev commented on test/functional/fixtures/reporter/test.js
> +        function customReporter (log) {
To simplify code, use the [createReporter](https://github.com/DevExpress/testcafe/blob/master/test/functional/utils/reporter.js) util method here.

2021-09-09 12:46 UTC, AndreyBelym approved these changes

2021-09-09 12:46 UTC, merged