feat: added more detailed information of report when running a *.testcafe fixture file using CLI
DevExpress/testcafe pull request #6484
Opened 2021-08-19 14:55 UTC by Aleksey28

[closes DevExpress/testcafe#6424]

## Purpose
Need to find out which step of the recorded (*.testcafe) test fails.

## Approach
1. Add test
2. Add showing additional information about the fail step of the test

## References
https://github.com/DevExpress/testcafe/issues/6424

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-08-24 15:14 UTC, miherlosev requested changes

2021-08-24 15:14 UTC, miherlosev commented on src/errors/runtime/index.js
> +        const renderers = this.callsite?.constructor.name === CALLSITE_RECORD_CLASS_NAME ? renderersRecord : renderersCommand;
Move this expression to the `getRenderes(callsite)` utility function and use it in all places.

2021-09-02 06:47 UTC, AndreyBelym approved these changes

2021-09-02 06:47 UTC, AndreyBelym commented
Please merge after 1.16.0 is out.

2021-09-08 13:20 UTC, merged