feat: Integrate dashboard reporter (closes #6657)
DevExpress/testcafe pull request #6658
Opened 2021-10-28 15:01 UTC by Dmitry-Ostashev

## Purpose
Integrate testcafe-reporter-dashboard with TestCafe. Develop an API.

## Approach
Pass options object to the reporter via plugin constructor aguments

## References
https://github.com/DevExpress/testcafe/issues/6657

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

2021-11-15 10:41 UTC, AndreyBelym approved these changes

2021-11-15 10:46 UTC, miherlosev requested changes

2021-11-15 10:46 UTC, miherlosev commented on src/runner/index.js
> +            return Promise.resolve();
`retrun`;

2021-11-15 10:46 UTC, miherlosev commented on src/runner/index.js
> +        return Promise.resolve();
Remove this line.

2021-11-15 14:00 UTC, miherlosev approved these changes

2021-11-16 11:12 UTC, AlexKamaev approved these changes

2021-11-16 11:16 UTC, merged