Should not close child window immediately after opening (attempt to fix 6680)
DevExpress/testcafe pull request #6687
Opened 2021-11-10 14:02 UTC by AlexKamaev

2021-11-12 07:59 UTC, miherlosev requested changes

2021-11-12 07:59 UTC, miherlosev commented on src/test-run/index.ts
> +    public async handleAttachment (options: { isOpenedInNewWindow: boolean }): Promise<void> {
I propose to rename the `options` parameters to `info` or `data`.

2021-11-16 11:17 UTC, miherlosev approved these changes

2021-11-16 13:40 UTC, Farfurix requested changes
It looks like we should remove `async` function here

2021-11-16 13:40 UTC, Farfurix commented on src/test-run/index.ts
> +    public async handleAttachment (data: { isOpenedInNewWindow: boolean }): Promise<void> {
```suggestion
    public handleAttachment (data: { isOpenedInNewWindow: boolean }): void {
```

2021-11-18 07:31 UTC, Farfurix approved these changes

2021-11-18 07:32 UTC, merged