split moveautomation
DevExpress/testcafe pull request #6698
Opened 2021-11-17 08:02 UTC by AlexKamaev

2021-11-19 09:06 UTC, LavrovArtem approved these changes
great

2021-11-22 11:56 UTC, miherlosev requested changes

2021-11-22 11:56 UTC, miherlosev commented on src/client/automation/playback/drag/base.js
> +import MoveWithDragAutomation from '../move/move-with-drag';
Rename `MoveWithDragAutomation` to `DragMoveAutomation`

2021-11-23 07:44 UTC, miherlosev approved these changes

2021-11-23 10:23 UTC, merged