refactoring: MoveAutomation. Removed unnecessary properties.
DevExpress/testcafe pull request #6700
Opened 2021-11-17 09:51 UTC by LavrovArtem

2021-11-17 10:17 UTC, miherlosev requested changes

2021-11-17 10:17 UTC, miherlosev commented on src/client/automation/get-element.js
> +                    corrected: correctedElement !== foundElement,
I propose to change the `corrected` work to the `isTarget`.

2021-11-17 10:58 UTC, miherlosev commented on src/client/automation/get-element.js
> +                    corrected: correctedElement !== foundElement,
We decided to fix it later.

2021-11-17 10:58 UTC, miherlosev approved these changes

2021-11-18 07:12 UTC, AlexKamaev approved these changes

2021-11-18 20:42 UTC, merged