feat: implemented cookies API
DevExpress/testcafe pull request #6707
Opened 2021-11-19 06:09 UTC by Farfurix

### TODO
- [ ] callsites assertion in functional tests
- [ ] fix server tests
- [ ] release a new hammerhead version
- [ ] check all added errors in tests
- [ ] vars and hardcoded names in templates
- [ ] check all flatten cases
- [ ] new URL(urlArgumentValue); // eslint-disable-line no-new
- [ ] check cookie validation functions

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-11-23 11:03 UTC, miherlosev requested changes

2021-11-23 11:03 UTC, miherlosev commented on src/test-run/index.ts
> +                        cookiesPromises.push(this.session.cookies.findCookieByApi(domain, path, name));
Can we change signature of `session.cookies.findCookieByApi` function to allowing it asset an array of arguments?

2021-11-23 11:46 UTC, Farfurix commented on src/api/test-controller/index.js
> +            hooks = flattenDeep(hooks);
Previosly, we had [the `flattenDeep as flatten` import](https://github.com/DevExpress/testcafe/pull/6707/files#diff-7bef381dd93d2a93756020c28b7c0ace5f4f51c99e7731e37e55ac6f20fc7326L7). In my case I need the original `flatten` method (one level deep). In this PR I imported original methods ([flatten](https://lodash.com/docs/4.17.15#flatten), [flattenDeep](https://lodash.com/docs/4.17.15#flattenDeep)), so there is no difference in behavior for hooks.

2021-11-23 11:50 UTC, Farfurix commented on src/test-run/commands/actions.d.ts
> +    public cookies: any;
Yes, it's already on the TODO list.

2021-11-30 14:21 UTC, miherlosev requested changes

2021-11-30 14:21 UTC, miherlosev commented on src/test-run/commands/validations/argument.js
> +export function cookieArgumentsToGetOrDelete (callsite, cookieArguments) {
Method names should start with the verb (`get`, `set`, `validate`, etc.)

2021-11-30 14:21 UTC, miherlosev commented on ts-defs-src/test-api/test-controller.d.ts
> +interface Cookie {
Let's add a public type definition after the feature is completely implemented. Now, just remove it.

2021-12-15 07:29 UTC, closed without merging