cdp: iframe managing
DevExpress/testcafe pull request #6718
Opened 2021-11-23 15:15 UTC by LavrovArtem

2021-11-23 15:41 UTC, miherlosev requested changes

2021-11-23 15:41 UTC, miherlosev commented on src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
> +                    ExecutionContext.initialize(client.Runtime, client.Page);
I guess we reduce the parameters count for the `ExecutionContext.initialize` function.
```js
ExecutionContext.initialize(client);
```

2021-11-23 16:18 UTC, miherlosev approved these changes

2021-11-24 07:40 UTC, AlexKamaev approved these changes

2021-11-24 13:08 UTC, merged