fix: fixed incorrect Page URL visited when running tests in parallel in one file with Role
DevExpress/testcafe pull request #6782
Opened 2021-12-20 11:18 UTC by Aleksey28

[closes DevExpress/testcafe#6041]

## Purpose
Fix incorrect Page URL visited when running tests in parallel in one file with Role

## Approach
1. Add the tests to fix
2. Add keeping redirect URL in the Role for each test

## References
https://github.com/DevExpress/testcafe/issues/6041

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-12-22 08:50 UTC, AlexKamaev commented on src/role/role.ts
> +            this.redirectUrl[testRun.test.id] = currentUrl;
Can we refactor this whole block as follows:
```JS
if (this.opts.preserveUrl) {
    this.redirectUrl = currentUrl;
} else {
    this.redirectUrl = this.redirectUrl || {};
    this.redirectUrl[testRun.test.id] = currentUrl;
}
```

???

2021-12-22 08:52 UTC, AlexKamaev commented on src/test-run/bookmark.ts
> +            if (this.role.redirectUrl) {
In previous code there was not `null ref` check.
Is the empty redirect url possible now?

2021-12-22 09:40 UTC, miherlosev requested changes

2021-12-22 09:40 UTC, miherlosev commented on src/test-run/bookmark.ts
> +                const redirectUrl = typeof this.role.redirectUrl === 'string'
The `preserveUrl` is flag that manages the `redirectUrls` content. So, let's use it.
```js
const redirectUrl = this.opts.preserveUrl
    ? this.role.redirectUrl
    : this.role.redirectUrl[this.testRun.test.id]
```

2021-12-22 09:40 UTC, miherlosev commented on test/functional/fixtures/concurrency/test.js
> +                        expect(timeline.getData()).eql(['/fixtures/concurrency/pages/first-page.html', '/fixtures/concurrency/pages/second-page.html']);
A long time ago, the `timeline` variable contains only time data . Now, it's not so.
Let's rename it to `testInfo`.

2021-12-22 12:20 UTC, miherlosev requested changes

2021-12-22 12:20 UTC, miherlosev commented on test/functional/fixtures/concurrency/test-info.js
> +module.exports = testInfo;
A little bit shorter
```js
const FileStorage = require('../../utils/file-storage');

module.exports = new FileStorage('test-info.json', __dirname);
```

2021-12-22 15:06 UTC, miherlosev approved these changes

2021-12-27 08:47 UTC, AlexKamaev approved these changes

2021-12-27 08:48 UTC, merged