fix browser hanging on close window while video is recording
DevExpress/testcafe pull request #6800
Opened 2021-12-24 10:59 UTC by AlexKamaev

2022-01-18 08:26 UTC, miherlosev requested changes

2022-01-18 08:26 UTC, miherlosev commented on src/browser/connection/gateway.ts
> +            connection.provider.closeBrowserChildWindow(connection.id)
Should we catch errors of the `connection.provider.closeBrowserChildWindow` method here?

2022-01-18 08:26 UTC, miherlosev commented on src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
> +        await delay(100);
Can we use here a more stable way to check that window is closed?

2022-01-18 08:26 UTC, miherlosev commented on src/browser/provider/plugin-host.js
> +    closeBrowserChildWindow (/*browserId*/) {
`async closeBrowserChildWindow (/*browserId*/) {}`

2022-02-28 11:19 UTC, AndreyBelym commented
/rebase

2022-03-22 09:43 UTC, AndreyBelym approved these changes

2022-03-25 08:27 UTC, AndreyBelym commented
/rebase

2022-03-29 07:35 UTC, merged