fix: added condition to repeat getting tab list while it is empty
DevExpress/testcafe pull request #6823
Opened 2022-01-20 07:43 UTC by Aleksey28

## Purpose
We try to get a tabs list of the browser until errors are disappeared. But errors are appearing while the browser isn't ready. After that, the browser in docker doesn't have enough time to get the list of tabs.

## Approach
Try to get the list of the tabs while it is empty.

## References
https://teams.microsoft.com/l/message/19:5eb4e942f0f946188ab14b3d8bf960f3@thread.skype/1641979833965?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=f74b7d18-34a4-4c78-b7d5-b56e55ce3236&parentMessageId=1641979833965&teamName=Teams%20Collaborations&channelName=TestCafe&createdTime=1641979833965

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-01-21 08:07 UTC, AlexKamaev approved these changes

2022-01-21 08:23 UTC, miherlosev requested changes

2022-01-21 08:23 UTC, miherlosev commented on test/server/parse-fixture-test.js
> +                lazyEql(structure, expected);
I suggest using the current approach for this case - [removing new fields](https://github.com/DevExpress/testcafe/pull/5760/files).

2022-01-24 10:31 UTC, miherlosev requested changes

2022-01-24 10:31 UTC, miherlosev commented on test/server/parse-fixture-test.js
> +                lazyEql(structure, expected);
The `lazyEql` is not necessary now. You can use the `expect().eql()` expression again.

2022-01-24 11:53 UTC, miherlosev approved these changes

2022-01-24 12:26 UTC, merged