Add error info to quarantine object (closes #6722)
DevExpress/testcafe pull request #6864
Opened 2022-02-10 11:48 UTC by Artem-Babich

2022-02-15 09:40 UTC, AlexKamaev requested changes

2022-02-15 09:40 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/test.js
> +};
Check this util
...\testcafe\test\functional\utils\reporter.js

2022-02-15 09:40 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/test.js
> +
delete this test

2022-02-15 09:40 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/testcafe-fixtures/index.js
> +            break;
Maybe we do not need the Errors.None case?

2022-02-15 09:40 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/testcafe-fixtures/index.js
> +});
delete

2022-02-15 09:40 UTC, AlexKamaev commented on src/reporter/index.ts
> +            }, testItem.quarantine);
Let use Object.assign instead on initializing reduce this testItem.quarantine

2022-02-15 15:21 UTC, AlexKamaev requested changes

2022-02-15 15:21 UTC, AlexKamaev commented on src/reporter/index.ts
> +
excessive empty line

2022-02-15 15:21 UTC, AlexKamaev commented on src/reporter/index.ts
> +                    browser.quarantineAttemptsTestRunIds = [];
browser.quarantineAttemptsTestRunIds = browser.quarantineAttemptsTestRunIds || []

2022-02-15 15:21 UTC, AlexKamaev commented on src/reporter/index.ts
> +                result[testRunId] = { passed, errors };
add empty line before assignment

2022-02-15 15:21 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/constants.js
> +    this.add = (alias) => {
no need in `(` and `)` around alias

2022-02-15 15:21 UTC, AlexKamaev commented on test/functional/fixtures/regression/gh-6722/test.js
> +    return expect(currentAttemptsCount).to.equal(expectedAttemptsCount) &&
No need to return anything from this function.
No need to add && between conditions.
It's better to write assertions line by line:
```
        expect(currentSuccessAttemptsCount).to.equal(expectedSuccessAttemptsCount);
        expect(currentFailedAttemptsCount).to.equal(expectedFailedAttemptsCount);
        expect(currentTestRunIdsCount).to.equal(attemptsCount * browsersCount);
```

2022-02-16 07:17 UTC, AlexKamaev approved these changes

2022-02-16 07:52 UTC, Dmitry-Ostashev approved these changes

2022-02-22 09:01 UTC, merged