feat: added cookies API (2 part)
DevExpress/testcafe pull request #6892
Opened 2022-02-22 09:49 UTC by Aleksey28

## Purpose
Implement synchronization of changing cookies with the client

## Approach
Only add tests for synchronization changed cookies with the client and adapt the old one. The functionality itself has been implemented in the hammerhead.

## References
[First part](https://github.com/DevExpress/testcafe/pull/6841)
[Corresponding PR in the hammerhead](https://github.com/DevExpress/testcafe-hammerhead/pull/2741)

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-02-25 10:00 UTC, miherlosev requested changes

2022-02-25 10:00 UTC, miherlosev commented on package.json
> +    "testcafe-hammerhead": "^24.5.15",
Use the fixed testcafe-hammerhead version - `24.5.15`;

2022-02-25 10:58 UTC, miherlosev approved these changes

2022-02-28 10:40 UTC, AndreyBelym approved these changes

2022-02-28 10:41 UTC, merged