Add baseUrl option (closes #1932)
DevExpress/testcafe pull request #6894
Opened 2022-02-24 16:29 UTC by Artem-Babich

2022-03-23 06:54 UTC, AlexKamaev approved these changes

2022-03-25 07:35 UTC, titerman approved these changes

2022-03-25 08:28 UTC, AndreyBelym commented
/rebase

2022-03-30 12:45 UTC, AndreyBelym commented on src/api/exportable-lib/index.js
>      },
Do not merge until docs are ready.

2022-06-10 12:35 UTC, Aleksey28 commented on src/cli/argument-parser.ts
> +            .option('--baseUrl <url>', 'set the base url for all tests')
You should use `kebab-case` for naming CLI options. It automatically converted to `camelCase` for the config.

2022-06-10 12:36 UTC, Aleksey28 requested changes
Please, process the comment and rebase

2022-06-22 06:21 UTC, Aleksey28 approved these changes

2022-07-08 16:56 UTC, merged

2022-07-19 11:30 UTC, Nisden commented
Is there a reason for not supporting baseUrl when using Role's?

2022-07-20 07:12 UTC, Artem-Babich commented
[https://github.com/DevExpress/testcafe/pull/6894](https://github.com/DevExpress/testcafe/pull/6894)

Hello @Nisden,

Supporting relative URLs in a Role is a separate task, like supporting relative URLs in any other functionality that allows you to use some URL. That is why currently the baseURL option does not work with roles. We have a separate GitHub issue regarding this enhancement: [Support relative urls in Roles](https://github.com/DevExpress/testcafe/issues/3406). You can leave your feedback there. We will be happy to implement this functionality in TestCafe after we collect enough user votes.