feat: added showing advertising about the Dashboard
DevExpress/testcafe pull request #6960
Opened 2022-04-04 13:50 UTC by Aleksey28

## Purpose
Present information about `TestCafe Dashboard` in the CLI

## Approach
Show information about `TestCafe Dashboard` after each run in CLI with each reporter except `dashboard` reporter.

## References

## Pre-Merge TODO
- [X] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-04-14 07:59 UTC, helen-dikareva commented
ping @miherlosev @titerman

2022-04-15 06:27 UTC, miherlosev requested changes

2022-04-15 06:27 UTC, miherlosev commented on src/runner/index.js
> +            .then(() => this._addDashBoardAdvertisementIfNeeded())
I propose to push the dashboard related code to one `then` callback.

```js
.then(() => {
    this._addDashboardReporterIfNeeded();
    this._addDashBoardAdvertisementIfNeeded();
}))
```

2022-04-15 06:27 UTC, miherlosev commented on src/runner/index.js
> +        if (!reporterOptions)
We need to show ads if the default `spec` reporter is used. At present, it does not happen.

`testcafe chrome test.js`

Add a test for this case.

2022-04-15 07:15 UTC, titerman commented on src/runner/index.js
> +            this._addAdvertisement('We are proud to announce the TestCafe Dashboard (https://dashboard.testcafe.io/), our web-based test report aggregator for TestCafe users.');
```suggestion
            this._addAdvertisement('We are proud to announce TestCafe Dashboard (https://dashboard.testcafe.io/), the ultimate web-based TestCafe report aggregator.');
```

2022-04-15 12:09 UTC, Aleksey28 commented
Пока не мерджим

2022-05-04 09:04 UTC, AndreyBelym approved these changes

2022-05-04 09:06 UTC, merged

2022-05-10 16:20 UTC, qualityshepherd commented
lame

2022-05-11 07:28 UTC, Aleksey28 commented
We made ads more selective in this [PR#7018](https://github.com/DevExpress/testcafe/pull/7018).