dummy dashboard token storage + mock + test (closes 358 in marketing repo)
DevExpress/testcafe pull request #6968
Opened 2022-04-06 12:23 UTC by AlexKamaev

2022-04-06 14:19 UTC, Dmitry-Ostashev approved these changes

2022-04-07 05:09 UTC, miherlosev requested changes

2022-04-07 05:09 UTC, miherlosev commented on src/runner/dashboard-config-storage/index.ts
> +        return Promise.resolve(null);
`return null;`

2022-04-07 05:09 UTC, miherlosev commented on test/server/runner-test.js
> +                    return Promise.resolve({
`return { token: 'bar' }`

2022-04-07 06:29 UTC, miherlosev approved these changes

2022-04-21 05:16 UTC, miherlosev commented
These changes were copied in the https://github.com/DevExpress/testcafe/pull/6975.

2022-04-21 05:16 UTC, closed without merging