Rename dashboard options
DevExpress/testcafe pull request #6976
Opened 2022-04-13 06:54 UTC by miherlosev

2022-04-13 13:39 UTC, Dmitry-Ostashev requested changes

2022-04-13 13:39 UTC, Dmitry-Ostashev commented on src/cli/argument-parser.ts
> +            this.opts.dashboardOptions = await getDashboardOptions(this.opts.dashboardOptions as string);
https://github.com/DevExpress/testcafe/blob/master/src/cli/cli.js#L120

The object names are not match (opts.dashboardOptions here and opts.dashboard in the file above). The CLI does not work at this moment.

How to check locally:

1. Update the testcafe-reporter-dashboard version to 0.2.6-rc.1
2. Build and pack testcafe into tarball
3. Install testcafe from the tarball to some test project
4. Run test from runner. It works:

```
const createTestCafe        = require('testcafe');
let runner                  = null;

createTestCafe('localhost', 9222, 9223)
    .then(testcafe => {
        runner = testcafe.createRunner();
    })
    .then(() => {
        return runner
            .src('test.js')
            .browsers(['chrome'])
            .dashboard({
                token: 'some-token'
            })
            .run();
    });
```
5. Run from CLI. The default spec reporter will be used:

`npx testcafe chrome test.js --dashboard-options token=some-token`

2022-04-14 07:42 UTC, helen-dikareva approved these changes

2022-04-14 08:52 UTC, Dmitry-Ostashev approved these changes

2022-04-14 10:50 UTC, merged