proxyless: request error handling (part #2)
DevExpress/testcafe pull request #7283
Opened 2022-09-08 11:34 UTC by miherlosev

2022-09-15 12:48 UTC, Aleksey28 requested changes

2022-09-15 12:48 UTC, Aleksey28 commented on test/functional/fixtures/page-error/test.js
> +            return runTests('./testcafe-fixtures/page-error-test.js', 'Do not handle', { shouldFail: true })
I reproduce this test in a separate project and it hung in the proxyless mode.

2022-09-19 06:19 UTC, Aleksey28 approved these changes

2022-09-26 08:35 UTC, AndreyBelym approved these changes

2022-09-26 10:16 UTC, merged