feat: upgraded visibility errors
DevExpress/testcafe pull request #7319
Opened 2022-10-04 12:28 UTC by Aleksey28

[closes #7310]

## Purpose
Show detailed information in errors when elements are not visible.  

## Approach
1. Research visibility cases
2. Refactor current visibility checks
3. Add tests
4. Add check when an element has the property `visibility: collapse`
5. Add rendering messages with detailed visibility information
6. Expand current errors templates with rendered messages

## References
#7310 

## Pre-Merge TODO
- [X] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-10-12 05:26 UTC, AndreyBelym approved these changes

2022-10-12 05:27 UTC, AndreyBelym commented on package.json
> +    "testcafe-legacy-api": "file:testcafe-legacy-api-5.1.5.tgz",
I will buplish a new legacy package today, please do not merge until then

2022-10-12 19:03 UTC, titerman requested changes

2022-10-20 13:33 UTC, titerman approved these changes

2022-11-02 08:08 UTC, merged