Introduce CustomActions feature
DevExpress/testcafe pull request #7393
Opened 2022-11-23 05:22 UTC by Artem-Babich

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-12-04 20:45 UTC, AndreyBelym approved these changes

2022-12-05 08:18 UTC, miherlosev requested changes

2022-12-05 08:18 UTC, miherlosev commented on test/server/runner-test.js
> +        it('Should raise an error if customActions property belongs to invalid type', async function () {
Add a test demonstrating reporting of custom actions.

2022-12-09 12:37 UTC, miherlosev requested changes

2022-12-09 12:37 UTC, miherlosev commented on src/reporter/command/command-formatter.ts
> +    PressKeyCommand, RunCustomActionCommand,
Move to the new line

2022-12-09 12:37 UTC, miherlosev commented on src/errors/runtime/templates.js
> +    [RUNTIME_ERRORS.invalidCustomActionsOptionType]:                 `The value of the customActions option does not belong to type Object. Refer to the following article for custom action setup inst
It's better adding `DOCUMENTATION_LINKS.CUSTOM_ACTIONS` constant [here](https://github.com/DevExpress/testcafe/pull/7393/files#diff-2b693f1a4eee477500a439748a3a10702958774c09ccd8813d36fa8bbffb3eb4L11) and use it in templates.

2022-12-09 12:37 UTC, miherlosev commented on src/reporter/command/command-formatter.ts
> +        if (this._result !== void 0)
I guess, we can always apply the action result even if it equals `undefined`.

2022-12-12 01:43 UTC, miherlosev requested changes

2022-12-12 01:43 UTC, miherlosev commented on src/reporter/command/command-formatter.ts
> +    private _prepareCustomActionResult (): unknown {
You can remove this function since it's used only in one place and contains only one instruction.

2022-12-12 07:19 UTC, miherlosev approved these changes

2022-12-14 07:32 UTC, merged