proxyless: rename proxyless option to nativeAutomation
DevExpress/testcafe pull request #7608
Opened 2023-04-03 07:40 UTC by Artem-Babich

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2023-04-03 09:23 UTC, miherlosev requested changes

2023-04-03 09:23 UTC, miherlosev commented on test/functional/fixtures/browser-provider/browser-reconnect/run-log-error-on-disconnect-test.js
> +            .run({ nativeAutomation: config.proxyless });
Rename the `config.proxyless` property and related test stuff.

2023-04-03 14:31 UTC, miherlosev requested changes

2023-04-03 14:31 UTC, miherlosev commented on gulp/helpers/test-functional.js
>      if (isProxyless)
Rename to `nativeAutomation` here too.

2023-04-03 14:31 UTC, miherlosev commented on test/functional/fixtures/api/es-next/iframe-switching/test.js
> +const { errorInEachBrowserContains }     = require('../../../../assertion-helper.js');
Fix align of the `=` symbols.

2023-04-03 14:31 UTC, miherlosev commented on test/functional/fixtures/api/es-next/upload/test.js
> +const path                       = require('path');
Fix align of the `=` symbols.

2023-04-03 14:31 UTC, miherlosev commented on test/functional/fixtures/api/json/test.js
> +const { skipInNativeAutomation } = require('../../../utils/skip-in');
Fix align of the `=` symbols.

2023-04-03 14:31 UTC, miherlosev commented on test/functional/fixtures/concurrency/test.js
> +const { skipInNativeAutomation } = require('../../utils/skip-in');
Fix align of the `=` symbols.

2023-04-03 14:31 UTC, miherlosev commented on test/functional/fixtures/proxy/test.js
> +const { expect }                 = require('chai');
Fix align of the `=` symbols.

2023-04-04 06:26 UTC, Artem-Babich commented on src/errors/runtime/templates.js
> +    [RUNTIME_ERRORS.setProxylessForUnsupportedBrowsers]:             'The following browser(s) do not support the Native Automation mode: {browsers}.',
yes

2023-04-04 06:26 UTC, Artem-Babich commented on src/cli/argument-parser/index.ts
> +            .option('--native-automation', 'enable native automation')
yes

2023-04-04 07:24 UTC, miherlosev approved these changes

2023-04-04 09:52 UTC, aleks-pro approved these changes

2023-04-04 09:53 UTC, merged