Add possibility to load config file from cjs file
DevExpress/testcafe pull request #7614
Opened 2023-04-06 12:02 UTC by gigaga

[closes #6911]

## Purpose
The newest NodeJS version requires indicating modules loading framework to use (CommonJS or ESM) by using extension file. `.js` extension is now for using ESM and `.cjs` for CommonJS.
Currently, from newest NodeJS, it is not possible to use CommonJS framework for TestCafe global configuration file (`.testcaferc.js`), because this file has to be named `.testcaferc.cjs`

## Approach
This PR allows loading `.testcaferc.cjs` as TestCafe global configuration file.

2023-04-07 08:05 UTC, Aleksey28 requested changes
Thank you for your contribution.

2023-04-10 05:39 UTC, Aleksey28 approved these changes

2023-04-10 06:18 UTC, miherlosev commented
@gigaga 

Please fix lint errors - https://github.com/DevExpress/testcafe/actions/runs/4654867081/jobs/8236970726

2023-04-11 08:50 UTC, gigaga commented
> [miherlosev](/miherlosev)

Hi !
It's done ;)

2023-04-12 10:39 UTC, Aleksey28 requested changes
Please fix server tests.

2023-04-12 12:19 UTC, gigaga commented
> Please fix server tests.

It's done. However, It is not possible to ensure that the whole of tests is ok because it seems not possible to be executed on local env. Isn't it?

Regards,

2023-04-13 09:27 UTC, Aleksey28 commented
It's possible. I see a lot of excessive formatting changes in the current version of the commit. Please roll back these changes.

2023-04-13 09:38 UTC, gigaga commented
Hi,

I fixed again lint issues... :(

2023-04-14 08:11 UTC, Aleksey28 commented
You still have a few ESLint errors. Please fix them.

2023-04-17 18:49 UTC, gigaga commented
Hi,
I'm not sure but I think that the tests are ko, it is not related to my changes.
Regards,

2023-04-20 07:24 UTC, miherlosev commented
> I'm not sure but I think that the tests are ko, it is not related to my changes.

Please run the `test-server` gulp task locally and fix the failed tests.

2023-04-20 10:50 UTC, gigaga commented
> > I'm not sure but I think that the tests are ko, it is not related to my changes.
> 
> Please run the `test-server` gulp task locally and fix the failed tests.

It is done ;)

2023-04-25 10:34 UTC, gigaga commented
The last issue is due to an invalid content in Docker image. Indeed, the content of `const Extensions            = require('../../lib/configuration/formats');` corresponds to the old value (came from original Docker image `FROM testcafe/testcafe:$tag` ?):
```
{
  JS_CONFIGURATION_EXTENSION: '.js',
  JSON_CONFIGURATION_EXTENSION: '.json',
  CONFIGURATION_EXTENSIONS: [ '.js', '.json' ]
}
```

And expected should be
```
{
  "js": ".js",
  "json": ".json",
  "cjs": ".cjs"
} 
```

So, the configurations made with `createJsTestCafeConfigurationFile` or `createJSONTestCafeConfigurationFile` are invalid because path is `undefined`.

I don't know how to fix it...

2023-04-27 02:13 UTC, miherlosev commented
Rebase please.

2023-04-28 07:45 UTC, gigaga commented
Hi @miherlosev 

- Before rebasing, I had some tests failed as describing before (old content of Docker image of `test/docker/Dockerfile`)

- After rebasing, the build of Docker image `test/docker/Dockerfile` is failed due to `Error: ENOENT: no such file or directory, open './package.json'`. I executed `npx gulp docker-server-test-run --steps-as-tasks`

Regards,

2023-05-03 07:40 UTC, merged

2023-05-03 07:59 UTC, gigaga commented
;)