proxyless: ignore the `paste` option of TypeAutomation
DevExpress/testcafe pull request #7617
Opened 2023-04-07 08:48 UTC by AlexKamaev

2023-04-11 02:14 UTC, miherlosev requested changes

2023-04-11 02:14 UTC, miherlosev commented on src/client/automation/playback/type/index.js
> +        if (this.nativeAutomationInput)
I propose using another way: if there is the `paste` option, don't use the `nativeAutomation` approach.

2023-04-11 06:49 UTC, aleks-pro approved these changes

2023-04-13 03:39 UTC, miherlosev approved these changes

2023-04-13 09:26 UTC, merged