native automation: disable multiple windows if native automation is enabled
DevExpress/testcafe pull request #7618
Opened 2023-04-07 15:02 UTC by AlexKamaev

2023-04-10 13:23 UTC, AlexKamaev commented
@titerman check the error message please

2023-04-12 02:13 UTC, miherlosev requested changes

2023-04-12 02:13 UTC, miherlosev commented on src/client/driver/driver.js
> +        if (this.options.nativeAutomation) {
Remove the one level of curly brackets.

```js
if (!this.options.nativeAutomation)
    return;

....
```

2023-04-12 02:13 UTC, miherlosev commented on test/functional/fixtures/regression/gh-7599/test.js
> +const expect                     = require('chai').expect;
```js
const { expect } = require('chai');
```

2023-04-13 03:41 UTC, miherlosev approved these changes

2023-04-13 09:45 UTC, titerman commented on src/errors/test-run/templates.js
> +        Multi-window mode is not supported in the Native Automation mode. To run test in multiple windows, please remove the "--native-automation" option.
```suggestion
        The Native Automation mode does not support the use of multiple browser windows. Disable the "native automation" option to continue.
```

2023-04-13 12:15 UTC, merged