Add: debug with selector option added
DevExpress/testcafe pull request #8066
Opened 2023-11-02 17:18 UTC by Bayheck

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2023-11-09 11:01 UTC, Aleksey28 requested changes
Good job!  Please look at my comments

2023-11-09 11:01 UTC, Aleksey28 commented on test/functional/fixtures/ui/testcafe-fixtures/selector-inspector-test.js
> +test('should indicate the correct number of elements matching the TestCafe selector passed in debug', async t => {
Your tests aren't executed. You should add them [here](https://github.com/DevExpress/testcafe/blob/d55e8b8145a1d32c9665893817295f6fa70e69ad/test/functional/fixtures/ui/test.js#L45)

2023-11-13 08:06 UTC, Aleksey28 requested changes
One more thing

2023-11-13 08:16 UTC, Aleksey28 approved these changes
Great, merge after the tests turn green

2023-11-14 11:33 UTC, aleks-pro commented
Please, do not merge. We need add documentation first.

2023-12-19 20:28 UTC, merged