remove endpoint-utils package
DevExpress/testcafe pull request #8217
Opened 2024-06-18 07:39 UTC by Bayheck

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2024-06-19 08:43 UTC, PavelMor25 commented on src/configuration/utils.ts
>      return hostname;
If the getIPAddress() method returns unidentified, should we handle this error here before proceeding?

@Aleksey28, What do you think about this?

2024-06-20 07:10 UTC, Aleksey28 requested changes

2024-06-20 14:36 UTC, Aleksey28 commented on src/utils/endpoint-utils.ts
> +} from 'net';
```suggestion
import {
    AddressInfo, 
    createServer, 
    Server,
} from 'net';
```

2024-06-21 05:38 UTC, PavelMor25 approved these changes

2024-06-25 07:00 UTC, Aleksey28 approved these changes

2024-06-25 13:50 UTC, aleks-pro approved these changes

2024-06-25 15:25 UTC, merged