fix:static class blocks are not enabled babel error
DevExpress/testcafe pull request #8267
Opened 2024-08-27 15:04 UTC by Bayheck

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2024-08-29 11:30 UTC, PavelMor25 approved these changes

2024-08-30 09:18 UTC, Aleksey28 requested changes
I don't think that it's regression, we haven't handled this kind of field before, moreover, I can't say that it's a fix, I think it's a small feature. So it's not the appropriate place for a test, also we already have some server compile tests [there ](https://github.com/DevExpress/testcafe/blob/master/test/server/compiler-test.js) and it's better to test this behavior there because functional tests are heavier than server tests

2024-09-02 06:14 UTC, Aleksey28 approved these changes

2024-09-06 06:40 UTC, Aleksey28 requested changes
Why did you fix the @types/node version?

2024-09-12 07:06 UTC, Aleksey28 approved these changes

2024-09-12 09:58 UTC, aleks-pro approved these changes

2024-09-16 07:12 UTC, merged