fix: updated babel packages
DevExpress/testcafe pull request #8281
Opened 2024-09-17 13:56 UTC by Bayheck

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
closes https://github.com/DevExpress/testcafe/issues/8272

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2024-09-24 06:34 UTC, Aleksey28 requested changes

2024-09-24 06:34 UTC, Aleksey28 commented on src/compiler/babel/load-libs.js
> +        proposalPrivateMethods:     [require('@babel/plugin-transform-private-methods'), { loose: true }],
Let's rename properties too

2024-09-26 07:06 UTC, Aleksey28 approved these changes

2024-09-26 09:37 UTC, PavelMor25 approved these changes

2024-09-30 07:05 UTC, merged